# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
language: swift  #1
osx_image: xcode9.2 #2
xcode_workspace: Example/MGImageExtension.xcworkspace #3
xcode_scheme: MGImageExtension-Example #4
xcode_destination: platform=iOS Simulator,OS=11.2,name=iPhone X
#xcode_sdk: iphonesimulator11.2 #5

#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/QRBot.xcworkspace -scheme QRBot-Example -sdk iphonesimulator11.2 ONLY_ACTIVE_ARCH=NO | xcpretty
